test:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost

development:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost

production:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost